#!/bin/bash

cd $(dirname "$0")

. common

echo "Creating 1 GiB filesystem"
dev=$(makefs 1024 2>>"$logfile")
mnt=$(mktemp -d)
loop=$(makeloop "$dev" "$mnt" 2>>"$logfile")
echo "Copying directory tree"
cp -rf . "$mnt"
cleanup "$mnt" "$loop"
echo -n "Path to list: "
read path
bin/readdir "$dev" "$path"
rm "$dev"
